channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - r-base=3.6.1
  - fastqc
  - pyyaml=3.11
  - biom-format
  - cutadapt
  - qiime
  - vsearch
  - mothur
  - wkhtmltopdf
  - pear
  - bioconductor-biostrings
  - bioconductor-shortread
  - r-ggplot2
  - krona
  - blast
  - seqtk
  - rdp_classifier
  - java-jdk
  - zip

